# Generated by Django 4.2.16 on 2024-09-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_response_question_response_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
