# Generated by Django 4.2.16 on 2024-09-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_answer_surveyresponse_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
