# Generated by Django 4.2.16 on 2024-09-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_survey_slug_alter_survey_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='slug',
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
